[package]
name = "mandelbrot_set"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.5"
clap = "4.4.11"
anyhow = "1.0.76"
num = "0.4.1"